-- Part 2: 20 Practice Join Questions (Unsolved)

-- Use the solved examples above as a guide to figure these out.

-- 1. Create CUSTOMERS Table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    CITY VARCHAR2(50),
    PHONE_NUMBER VARCHAR2(20),
    LOYALTY_POINTS NUMBER
);

-- 2. Create ORDERS Table
CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    ORDER_DATE DATE,
    TOTAL_AMOUNT NUMBER(10, 2),
    DISCOUNT_AMT NUMBER(10, 2), -- Can be NULL if no discount
    SHIPPING_DATE DATE          -- Can be NULL if not shipped yet
);

-- 3. Insert Data with intentional NULL values

-- Customers
INSERT INTO CUSTOMERS VALUES (101, 'John', 'Doe', 'New York', '555-0100', 500);
INSERT INTO CUSTOMERS VALUES (102, 'Jane', 'Smith', NULL, '555-0101', 120);
INSERT INTO CUSTOMERS VALUES (103, 'Robert', 'Brown', 'Chicago', NULL, 0);
INSERT INTO CUSTOMERS VALUES (104, 'Emily', 'Davis', NULL, NULL, NULL); -- Lots of NULLs
INSERT INTO CUSTOMERS VALUES (105, 'Michael', 'Wilson', 'Miami', '555-0105', NULL);

-- Orders
INSERT INTO ORDERS VALUES (5001, 101, DATE '2023-10-01', 150.00, 10.00, DATE '2023-10-03');
INSERT INTO ORDERS VALUES (5002, 102, DATE '2023-10-02', 200.50, NULL, DATE '2023-10-05'); -- No discount
INSERT INTO ORDERS VALUES (5003, 101, DATE '2023-10-05', 75.00, 5.00, NULL); -- Not shipped
INSERT INTO ORDERS VALUES (5004, 104, DATE '2023-10-06', 300.00, NULL, NULL); -- No discount, Not shipped
INSERT INTO ORDERS VALUES (5005, 105, DATE '2023-10-07', 50.00, 0.00, DATE '2023-10-08');
INSERT INTO ORDERS VALUES (5006, NULL, DATE '2023-10-08', 20.00, NULL, DATE '2023-10-09'); -- Orphan order

COMMIT;


-- 1. (Inner Join) List the FIRST_NAME of the customer and the TOTAL_AMOUNT for all orders that have a Discount (DISCOUNT_AMT is not null).

-- SELECTING COLUMNS TO DISPLAY
SELECT C.FIRST_NAME, O.TOTAL_AMOUNT
-- SELECT TABLE
FROM CUSTOMERS C
-- JOINING TABLE
INNER JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID -- MATCHING BOTH COMMON COLUMNS 
WHERE O.DISCOUNT_AMT IS NOT NULL; -- ADDING CONDITION

-- 2. (Left Join) List all Customers. If they have an order, display the ORDER_DATE. If not, ensure the row still appears with a NULL date.

-- SELECTING COLUMNS TO DISPLAY
SELECT C.FIRST_NAME, O.ORDER_DATE
-- SELECT TABLE
FROM CUSTOMERS C
-- JOINING TABLE
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID; -- MATCHING BOTH COMMON COLUMNS 

-- 3. (Right Join) Display ORDER_ID and FIRST_NAME. We want to see all orders, including the one with CUSTOMER_ID NULL (Order 5006).

-- SELECTING COLUMNS TO DISPLAY
SELECT O.ORDER_ID, C.FIRST_NAME
-- SELECT TABLE
FROM CUSTOMERS C
-- JOINING TABLE
RIGHT JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID; -- MATCHING BOTH COMMON COLUMNS 

-- 4. (Full Outer Join) Find the count of rows returned when you Full Outer Join Customers and Orders. (Try to predict the number before running it).

-- SELECTING COLUMNS TO DISPLAY
SELECT COUNT(*)
-- SELECT TABLE
FROM CUSTOMERS C
-- JOINING TABLE
FULL OUTER JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID; -- MATCHING BOTH COMMON COLUMNS 

-- 5. (Left Join - Anti Join) Find the CUSTOMER_IDs that exist in the CUSTOMERS table but do NOT exist in the ORDERS table.

-- SELECTING COLUMNS TO DISPLAY
SELECT C.CUSTOMER_ID
-- SELECT TABLE
FROM CUSTOMERS C
-- JOINING TABLE
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID -- MATCHING BOTH COMMON COLUMNS 
WHERE O.CUSTOMER_ID IS NULL; -- APPLYING CONDITION IS NULL

-- 6. (Self Join) Find pairs of Orders (O1, O2) that were placed on the exact same ORDER_DATE.

-- SELECTING COLUMNS TO DISPLAY
SELECT O1.ORDER_ID, O2.ORDER_ID, O1.ORDER_DATE
-- COMPARINT TWO COLUMNS IN ONE TABLE
FROM ORDERS O1
JOIN ORDERS O2
ON O1.ORDER_DATE = O2.ORDER_DATE
AND O1.ORDER_ID <> O2.ORDER_ID; -- MATCHING BOTH COMMON COLUMNS AND COMPARING

-- 7. (Cross Join) Create a list showing every Customer paired with every unique CITY found in the Customer table.

-- SELECTING COLUMNS TO DISPLAY
SELECT C.FIRST_NAME, CITIES.CITY
-- SELECT TABLE
FROM CUSTOMERS C
-- JOINING TABLE
CROSS JOIN (SELECT DISTINCT CITY FROM CUSTOMERS) CITIES; -- DISTINCT GIVES UNIQUE VALUE

-- 8. (Inner Join + Aggregates) Calculate the total DISCOUNT_AMT given to customers living in 'New York'.

-- SELECTING COLUMNS TO DISPLAY
SELECT SUM(O.DISCOUNT_AMT) AS TOTAL_DISCOUNT
-- SELECT TABLE
FROM CUSTOMERS C
-- JOINING TABLE
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID -- MATCHING BOTH COMMON COLUMNS 
WHERE C.CITY = 'New York'; -- APPLYING CONDITION ON 'NEW YORK' CITY

-- 9. (Left Join + NVL) Select FIRST_NAME and the SHIPPING_DATE. If the shipping date is NULL (either because the order isn't shipped OR the customer has no order), display 'Not Shipped'.

-- SELECTING COLUMNS TO DISPLAY
SELECT C.FIRST_NAME,
NVL(TO_CHAR(O.SHIPPING_DATE), 'Not Shipped') AS SHIPPING_STATUS
-- SELECT TABLE
FROM CUSTOMERS C
-- JOINING TABLE
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID; -- MATCHING BOTH COMMON COLUMNS 

-- 10. (Right Join) Find the sum of TOTAL_AMOUNT for orders that do not have a linked Customer (Orphan orders).

-- SELECTING COLUMNS TO DISPLAY
SELECT SUM(O.TOTAL_AMOUNT)
-- SELECT TABLE
FROM CUSTOMERS C
-- JOINING TABLE
RIGHT JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID -- MATCHING BOTH COMMON COLUMNS 
WHERE C.CUSTOMER_ID IS NULL; -- APPLYING CONDITION IS NULL

-- 11. (Natural Join) Use a Natural Join to display LAST_NAME and TOTAL_AMOUNT. (Be careful: does LOYALTY_POINTS exist in both tables? No? Then it uses CUSTOMER_ID).

-- SELECTING COLUMNS TO DISPLAY
SELECT LAST_NAME, TOTAL_AMOUNT
-- SELECT TABLE
FROM CUSTOMERS
-- JOINING TABLE
NATURAL JOIN ORDERS; --COMBINES ROWS FROM TWO TABLES BASED ON ALL COLUMNS

-- 12. (Left Join with Multiple Conditions) Join Customers to Orders, but ONLY link orders where the TOTAL_AMOUNT is greater than 100. Customers with small orders should look like they have NULL orders.

-- SELECTING COLUMNS TO DISPLAY
SELECT C.FIRST_NAME, O.ORDER_ID, O.TOTAL_AMOUNT
-- SELECT TABLE
FROM CUSTOMERS C
-- JOINING TABLE
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID -- MATCHING BOTH COMMON COLUMNS 
AND O.TOTAL_AMOUNT > 100; -- APPLYING CONDITION OF > 100

-- 13. (Inner Join) List FIRST_NAME and ORDER_ID for customers who have a Phone Number (IS NOT NULL).

-- SELECTING COLUMNS TO DISPLAY
SELECT C.FIRST_NAME, O.ORDER_ID
-- SELECT TABLE
FROM CUSTOMERS C
-- JOINING TABLE
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID -- MATCHING BOTH COMMON COLUMNS 
WHERE C.PHONE_NUMBER IS NOT NULL; -- APPLYING IS NOT NULL CONDITION

-- 14. (Full Join + Coalesce) Display a list of IDs. If it's a Customer without an order, show Customer ID. If it's an Order without a Customer, show Order ID. Use COALESCE.

-- SELECTING COLUMNS TO DISPLAY
SELECT COALESCE(C.CUSTOMER_ID, O.ORDER_ID) AS ID_VALUE
-- SELECT TABLE
FROM CUSTOMERS C
-- JOINING TABLE
FULL OUTER JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID; -- MATCHING BOTH COMMON COLUMNS 

-- 15. (Self Join) Find customers who have the same LOYALTY_POINTS value as another customer.

-- SELECTING COLUMNS TO DISPLAY
SELECT C1.FIRST_NAME, C2.FIRST_NAME, C1.LOYALTY_POINTS
-- SELECT TABLE
FROM CUSTOMERS C1
-- JOINING TABLE
JOIN CUSTOMERS C2
ON C1.LOYALTY_POINTS = C2.LOYALTY_POINTS -- MATCHING BOTH COMMON COLUMNS 
AND C1.CUSTOMER_ID <> C2.CUSTOMER_ID; -- COMPARING

-- 16. (Inner Join) Display FIRST_NAME, CITY, and ORDER_DATE for orders that have actually been shipped (SHIPPING_DATE is not null).

-- SELECTING COLUMNS TO DISPLAY
SELECT C.FIRST_NAME, C.CITY, O.ORDER_DATE
-- SELECT TABLE
FROM CUSTOMERS C
-- JOINING TABLE
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID -- MATCHING BOTH COMMON COLUMNS 
WHERE O.SHIPPING_DATE IS NOT NULL; -- APPLYING CONDITION IS NOT NULL

-- 17. (Left Join) Calculate the Average TOTAL_AMOUNT per Customer. Ensure customers with no orders show up (likely as NULL or 0 depending on how you write the Average).

-- SELECTING COLUMNS TO DISPLAY
SELECT C.FIRST_NAME, C.CITY, O.ORDER_DATE
-- SELECT TABLE
FROM CUSTOMERS C
-- JOINING TABLE
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID -- MATCHING BOTH COMMON COLUMNS 
WHERE O.SHIPPING_DATE IS NOT NULL; -- APPLYING CONDITION IS NOT NULL

-- 18. (Cartesian/Cross) Count how many rows are generated if you Cross Join CUSTOMERS (5 rows) and ORDERS (6 rows).

-- SELECTING COUNT(ALL)
SELECT COUNT(*)
-- SELECT TABLE
FROM CUSTOMERS
-- JOINING TABLE
CROSS JOIN ORDERS;

-- 19. (Join with Date Comparison) Find Customers who placed an order on the same day their account was created? (Wait, we don't have account creation date.Instead: Find Orders placed after the shipping date? This checks for data errors).

-- SELECTING ALL USING (*)
SELECT *
-- SELECT TABLE
FROM ORDERS
WHERE ORDER_DATE > SHIPPING_DATE; -- APPLYING > CONDITION

-- 20. (Three-way Simulation) Advanced Challenge: Perform a Left Join from Customers to Orders, and then Self Join that result to find Customers who have placed more than one order. Colab paid products - Cancel contracts here

-- SELECTING COLUMNS TO DISPLAY
SELECT C.FIRST_NAME, COUNT(O.ORDER_ID) AS ORDER_COUNT -- USING COUNT() TO COUNT ORDER_ID
-- SELECT TABLE
FROM CUSTOMERS C
-- JOINING TABLE
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID -- MATCHING BOTH COMMON COLUMNS 
-- USING GROUP BY TO GET DATA OF EACH PERSON
GROUP BY C.FIRST_NAME
-- USING HAVING TO GET GREATER THAN 1 ORDER
HAVING COUNT(O.ORDER_ID) > 1;